### ISSUE TITLE
element tests take a very long time to pass

### ISSUE THREAD

**Issue by OR13** [transmute-industries/sidetree.js#112]
probably a combination of factors, would love to get them to be faster.

**Comment by gjgd** [comment]
This is because most of the tests recreate the element server between every tests (with `beforeEach` not `beforeAll`). See https://github.com/transmute-industries/sidetree.js/blob/master/packages/did-method-element/src/__test__/dif-test-vector-conformance.spec.ts#L24

Creating and initializing an element test server takes a long time so finding a way to reset it without recreating it will help

**Comment by OR13** [comment]
wonder if the intermittent CI seg faults are related to this as well.

**Comment by BenjaminMoe** [comment]
This is stale. Closing. We can re-open this issue if we think tests are taking too long.
