### ISSUE TITLE
Unable to run test

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/sidetree.js#212]
I got the error as below when running the test

Nodejs version 16

![image](https://user-images.githubusercontent.com/5725085/125711835-6ff3760e-5d5c-427e-a604-4f0adc695e0b.png)

**Comment by BenjaminMoe** [comment]
I think this was address by the inclusion of `jest.config.js` https://github.com/transmute-industries/sidetree.js/blob/main/packages/cas/jest.config.js#L5. What happens is that jest seems to use it's own version of nodejs, which is/was version 12 where TextDecoder is not yet included by default. Since defining a jest envitronment file, this error shouldn't be showing up anymore: https://github.com/transmute-industries/sidetree.js/blob/main/packages/cas/custom-jest-node-environment.js. 

More Information about this error can be found here:
https://github.com/facebook/jest/issues/2549
