### ISSUE TITLE
Bug report: Building Elem locally

### ISSUE THREAD

**Issue by bumblefudge** [transmute-industries/sidetree.js#326]
https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-element/docs/local-dev.md#start-required-services

^ dev:elem doesn't, exist, did:ganache returns this
``` 
Server Error
Error: Error serializing `.method` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

I'm on WSL2 (Ubuntu 20), fwiw.

**Comment by BenjaminMoe** [comment]
Thanks for the report! This documentation predates some changes that were made to the `package.json` file in the `dashboard` package. 

The commands after **Start Element** should be:
```
$ cd packages/dashboard
$ cp .env.ganache.example .env.ganache
$ npm run dev:ganache
```

I'll do more testing locally and update the documentation. Let me know if there's anything else that needs to be fixed.

**Comment by bumblefudge** [comment]
OK great, that gets me to here
![image](https://user-images.githubusercontent.com/37127325/146833350-a750ce0c-3b64-4bc7-8e01-862db527a901.png)

But once I'm there, I am getting seeing a lot of Invalid JSON RPC response errors during the minutes-long DID creation in the GUI.  To wit:

```
info  - ready on http://localhost:3000
error - .next/server/pages/api/1.0/operations.js (43:0) @ Object.InvalidResponse
Error: Invalid JSON RPC response: ""
  41 |     InvalidResponse: function (result) {
  42 |         var message = !!result && !!result.error && !!result.error.message ? result.error.message : 'Invalid JSON RPC response: ' + JSON.stringify(result);
> 43 |         return new Error(message);
  44 |     },
  45 |     ConnectionTimeout: function (ms) {
  46 |         return new Error('CONNECTION TIMEOUT: timeout of ' + ms + ' ms achived');
```

Similarly, I opened a new WSL2 terminal and tried `curl --header "Content-Type: application/json" --request POST --data '{"type":"create",...`, and got this back:

```
<!DOCTYPE html><html><head><style data-next-hide-fouc="true">body{display:none}</style><noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript><link href="https://fonts.googleapis.com/css?family=Lato:400,700|Rajdhani:500,700|Roboto+Condensed:400,700" rel="stylesheet"/><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1640034686969"></script><script src="/_next/static/chunks/webpack.js?ts=1640034686969" defer=""></script><script src="/_next/static/chunks/main.js?ts=1640034686969" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1640034686969" defer=""></script><script src="/_next/static/chunks/pages/_error.js?ts=1640034686969" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1640034686969" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1640034686969" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><div id="__next"></div><script src="/_next/static/chunks/react-refresh.js?ts=1640034686969"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{"__NEXT_PAGE":"/api/1.0/operations"},"buildId":"development","isFallback":false,"err":{"name":"Error","message":"Invalid JSON RPC response: \"\"","stack":"Error: Invalid JSON RPC response: \"\"\n    at Object.InvalidResponse (/home/juancho/sidetree.js/packages/dashboard/.next/server/pages/api/1.0/operations.js:662267:16)\n    at XMLHttpRequest.request.onreadystatechange (/home/juancho/sidetree.js/packages/dashboard/.next/server/pages/api/1.0/operations.js:680197:32)\n    at XMLHttpRequest.module.exports.../did-method-element/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js.XMLHttpRequestEventTarget.dispatchEvent (/home/juancho/sidetree.js/packages/dashboard/.next/server/pages/api/1.0/operations.js:686332:22)\n    at XMLHttpRequest.module.exports.../did-method-element/node_modules/xhr2-cookies/dist/xml-http-request.js.XMLHttpRequest._setReadyState (/home/juancho/sidetree.js/packages/dashboard/.next/server/pages/api/1.0/operations.js:686647:14)\n    at XMLHttpRequest.module.exports.../did-method-element/node_modules/xhr2-cookies/dist/xml-http-request.js.XMLHttpRequest._onHttpRequestError (/home/juancho/sidetree.js/packages/dashboard/.next/server/pages/api/1.0/operations.js:686788:14)\n    at ClientRequest.\u003canonymous\u003e (/home/juancho/sidetree.js/packages/dashboard/.next/server/pages/api/1.0/operations.js:686691:61)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at Socket.socketErrorListener (_http_client.js:475:9)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"gip":true,"scriptLoader":[]}</script></body></html>
```

**Comment by bumblefudge** [comment]
also sometimes this guy 😭
![image](https://user-images.githubusercontent.com/37127325/146835646-1dbdcfc9-6d87-4803-96a5-958e38456dc6.png)

**Comment by bumblefudge** [comment]
And after enough clicking around and testing, JS itself collapses into a heap
![image](https://user-images.githubusercontent.com/37127325/146835808-0ac6b7d5-c3a1-43ba-a994-7e4b333ab80e.png)

**Comment by BenjaminMoe** [comment]
For the RPC error, it looks like that's a result of `ganache-cli` not running. I think I worded it pretty poorly in the documentation, You'll need two terminals open. One running `ganachi-cli` to have the RPC open, and one running `npm run dev:ganache` to run the dashboard. 

Alternatively to run `ganache-cli` in the background, you can run `$ screen -dm bash -c "ganache-cli"`. 

For the heap issue, this can be fixed by changing the `dev:gache` package.json command from
```
"dev:ganache": "dotenv -e .env.ganache next dev",
```
to
```
"dev:ganache": "NODE_OPTIONS=--max_old_space_size=4096 dotenv -e .env.ganache next dev",
```

I'll include this in my next revision. Testing locally and I think there maybe an issue with the cache not being initialized after that.

**Comment by bumblefudge** [comment]
Yup, I got the same error once I opened ganache in a second terminal

**Comment by BenjaminMoe** [comment]
Tracked down the ipfs issue, which took a little longer to find a "simple" error that I would have liked.

```
error - TypeError [ERR_INVALID_URL]: Invalid URL: http://127.0.0.1:5001'
    at new NodeError (internal/errors.js:322:7)
```

The problem here is that it looks like `http://127.0.0.1:5001'` is the URL attempting to be used for IPFS, and it's invalid because it contains a single quotation on the end. The weird part is the value in the `.env.ganache.example` _should_ be correct as that's the value i've been using in my ropsten tests, which should work. I tried taking out the single quotations in the `.env.ganache` file

```
ELEMENT_CONTENT_ADDRESSABLE_STORE_SERVICE_URI=/ip4/127.0.0.1/tcp/5001
```

And that worked. Just out of curiosity, I wondered if there was something weird going on in the file, so I opened the working version and the non-working version in a hex editor. 

![Screenshot from 2021-12-21 09-49-12](https://user-images.githubusercontent.com/86194145/146852676-b743939c-2e5f-409a-becd-c2b7d2c0b4f1.png)

And it looks like the difference is the working version only has '\n', while the non-working version has '\r\n' between lines. So I guess that might cause an issue with how the env file is read. I'll try testing without the quotations and add that to the pull request. Maybe try it locally to see if it solves your issue, I was able to create a did after fixing this on my end.

**Comment by bumblefudge** [comment]
That worked for me too! Even on the `\r\n`-strewn hellscape of WSL2! I think when you stitch together this many complex systems it's just inevitable that env variables and line-endings and other devilish devops details sneak in to spoil the fun. Thanks for the rapid turnaround!

**Comment by BenjaminMoe** [comment]
Great, it looks like things worked out!
